"""Add Phase 2 collaboration tables: trip_members, trip_invitations, activity_logs, comments

Revision ID: 610c71206b38
Revises: 95c61d908440
Create Date: 2025-11-11 18:05:15.062617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610c71206b38'
down_revision: Union[str, None] = '95c61d908440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_days', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'notes')
    op.drop_column('trip_days', 'notes')
    # ### end Alembic commands ###
