"""create_missing_collaboration_tables

Revision ID: 66d3b9e05e39
Revises: 610c71206b38
Create Date: 2026-01-09 14:09:49.697753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66d3b9e05e39'
down_revision: Union[str, None] = '610c71206b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', postgresql.ENUM('TRIP_CREATED', 'TRIP_UPDATED', 'TRIP_DELETED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'MEMBER_ROLE_CHANGED', 'DAY_ADDED', 'DAY_UPDATED', 'DAY_DELETED', 'ACCOMMODATION_ADDED', 'ACCOMMODATION_UPDATED', 'TRANSIT_ADDED', 'ACTIVITY_ADDED', 'BOOKING_ADDED', 'EXPENSE_ADDED', 'NOTE_ADDED', 'CHECKLIST_COMPLETED', 'COMMENT_ADDED', name='activity_log_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_activity_type'), 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index('ix_activity_logs_trip_created', 'activity_logs', ['trip_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_trip_id'), 'activity_logs', ['trip_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_trip_entity', 'comments', ['trip_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_comments_trip_id'), 'comments', ['trip_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('trip_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', name='member_role'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='invitation_status'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('responded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_invitations_id'), 'trip_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_trip_invitations_invitee_email'), 'trip_invitations', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_trip_invitations_invitee_id'), 'trip_invitations', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_trip_invitations_inviter_id'), 'trip_invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_trip_invitations_status'), 'trip_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_trip_invitations_token'), 'trip_invitations', ['token'], unique=True)
    op.create_index(op.f('ix_trip_invitations_trip_id'), 'trip_invitations', ['trip_id'], unique=False)
    op.create_table('trip_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='memberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_trip_member')
    )
    op.create_index(op.f('ix_trip_members_id'), 'trip_members', ['id'], unique=False)
    op.create_index(op.f('ix_trip_members_trip_id'), 'trip_members', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_members_user_id'), 'trip_members', ['user_id'], unique=False)
    op.alter_column('activities', 'activity_type',
               existing_type=postgresql.ENUM('sightseeing', 'dining', 'adventure', 'cultural', 'entertainment', 'shopping', 'relaxation', 'transportation', 'accommodation', 'business', 'other', name='activity_type'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('activities', 'status',
               existing_type=postgresql.ENUM('planned', 'booked', 'completed', 'cancelled', name='activity_status'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('planned', 'booked', 'completed', 'cancelled', name='activity_status'),
               existing_nullable=False)
    op.alter_column('activities', 'activity_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('sightseeing', 'dining', 'adventure', 'cultural', 'entertainment', 'shopping', 'relaxation', 'transportation', 'accommodation', 'business', 'other', name='activity_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_trip_members_user_id'), table_name='trip_members')
    op.drop_index(op.f('ix_trip_members_trip_id'), table_name='trip_members')
    op.drop_index(op.f('ix_trip_members_id'), table_name='trip_members')
    op.drop_table('trip_members')
    op.drop_index(op.f('ix_trip_invitations_trip_id'), table_name='trip_invitations')
    op.drop_index(op.f('ix_trip_invitations_token'), table_name='trip_invitations')
    op.drop_index(op.f('ix_trip_invitations_status'), table_name='trip_invitations')
    op.drop_index(op.f('ix_trip_invitations_inviter_id'), table_name='trip_invitations')
    op.drop_index(op.f('ix_trip_invitations_invitee_id'), table_name='trip_invitations')
    op.drop_index(op.f('ix_trip_invitations_invitee_email'), table_name='trip_invitations')
    op.drop_index(op.f('ix_trip_invitations_id'), table_name='trip_invitations')
    op.drop_table('trip_invitations')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_trip_id'), table_name='comments')
    op.drop_index('ix_comments_trip_entity', table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_trip_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_trip_created', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
