"""Add expenses, trip_notes, packing_lists, and checklists features

Revision ID: 95c61d908440
Revises: d486d45f5ea2
Create Date: 2025-11-11 13:30:49.927867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c61d908440'
down_revision: Union[str, None] = 'd486d45f5ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ENUM('ACCOMMODATION', 'TRANSPORTATION', 'FOOD_DRINK', 'ACTIVITIES', 'SHOPPING', 'ENTERTAINMENT', 'HEALTH', 'INSURANCE', 'VISAS_FEES', 'GEAR_EQUIPMENT', 'COMMUNICATIONS', 'TIPS_GRATUITIES', 'EMERGENCY', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('budgeted_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_categories_category'), 'budget_categories', ['category'], unique=False)
    op.create_index(op.f('ix_budget_categories_id'), 'budget_categories', ['id'], unique=False)
    op.create_index(op.f('ix_budget_categories_trip_id'), 'budget_categories', ['trip_id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checklist_type', postgresql.ENUM('PRE_DEPARTURE', 'BOOKING_CONFIRMATIONS', 'DOCUMENTS', 'SHOPPING', 'GENERAL', 'CUSTOM', name='checklist_type'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_checklist_type'), 'checklists', ['checklist_type'], unique=False)
    op.create_index(op.f('ix_checklists_created_by'), 'checklists', ['created_by'], unique=False)
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_index(op.f('ix_checklists_trip_id'), 'checklists', ['trip_id'], unique=False)
    op.create_table('packing_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_lists_created_by'), 'packing_lists', ['created_by'], unique=False)
    op.create_index(op.f('ix_packing_lists_id'), 'packing_lists', ['id'], unique=False)
    op.create_index(op.f('ix_packing_lists_trip_id'), 'packing_lists', ['trip_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_due_date'), 'checklist_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_items_is_completed'), 'checklist_items', ['is_completed'], unique=False)
    op.create_table('packing_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('packing_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', postgresql.ENUM('CLOTHING', 'TOILETRIES', 'ELECTRONICS', 'DOCUMENTS', 'MEDICATIONS', 'ACCESSORIES', 'ENTERTAINMENT', 'SPORTS_GEAR', 'CAMPING_GEAR', 'BABY_ITEMS', 'FOOD_SNACKS', 'OTHER', name='packing_category'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_packed', sa.Boolean(), nullable=False),
    sa.Column('packed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_items_category'), 'packing_items', ['category'], unique=False)
    op.create_index(op.f('ix_packing_items_id'), 'packing_items', ['id'], unique=False)
    op.create_index(op.f('ix_packing_items_is_packed'), 'packing_items', ['is_packed'], unique=False)
    op.create_index(op.f('ix_packing_items_packing_list_id'), 'packing_items', ['packing_list_id'], unique=False)
    op.create_table('trip_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_day_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', postgresql.ENUM('GENERAL', 'JOURNAL', 'PLANNING', 'IMPORTANT', 'TIPS', 'MEMORIES', name='note_type'), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_notes_created_by'), 'trip_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_trip_notes_id'), 'trip_notes', ['id'], unique=False)
    op.create_index(op.f('ix_trip_notes_is_pinned'), 'trip_notes', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_trip_notes_note_type'), 'trip_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_trip_notes_trip_day_id'), 'trip_notes', ['trip_day_id'], unique=False)
    op.create_index(op.f('ix_trip_notes_trip_id'), 'trip_notes', ['trip_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_day_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('transit_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('category', postgresql.ENUM('ACCOMMODATION', 'TRANSPORTATION', 'FOOD_DRINK', 'ACTIVITIES', 'SHOPPING', 'ENTERTAINMENT', 'HEALTH', 'INSURANCE', 'VISAS_FEES', 'GEAR_EQUIPMENT', 'COMMUNICATIONS', 'TIPS_GRATUITIES', 'EMERGENCY', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('payment_method', postgresql.ENUM('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'DIGITAL_WALLET', 'BANK_TRANSFER', 'TRAVELER_CHECK', 'OTHER', name='payment_method'), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_time', sa.String(length=5), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transit_id'], ['transits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_paid_by_user_id'), 'expenses', ['paid_by_user_id'], unique=False)
    op.create_index(op.f('ix_expenses_trip_day_id'), 'expenses', ['trip_day_id'], unique=False)
    op.create_index(op.f('ix_expenses_trip_id'), 'expenses', ['trip_id'], unique=False)
    op.create_table('expense_splits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_splits_expense_id'), 'expense_splits', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_id'), 'expense_splits', ['id'], unique=False)
    op.create_index(op.f('ix_expense_splits_user_id'), 'expense_splits', ['user_id'], unique=False)
    op.drop_column('trip_days', 'notes')
    op.drop_column('trips', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_expense_splits_user_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_expense_id'), table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_expenses_trip_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_trip_day_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_paid_by_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_trip_notes_trip_id'), table_name='trip_notes')
    op.drop_index(op.f('ix_trip_notes_trip_day_id'), table_name='trip_notes')
    op.drop_index(op.f('ix_trip_notes_note_type'), table_name='trip_notes')
    op.drop_index(op.f('ix_trip_notes_is_pinned'), table_name='trip_notes')
    op.drop_index(op.f('ix_trip_notes_id'), table_name='trip_notes')
    op.drop_index(op.f('ix_trip_notes_created_by'), table_name='trip_notes')
    op.drop_table('trip_notes')
    op.drop_index(op.f('ix_packing_items_packing_list_id'), table_name='packing_items')
    op.drop_index(op.f('ix_packing_items_is_packed'), table_name='packing_items')
    op.drop_index(op.f('ix_packing_items_id'), table_name='packing_items')
    op.drop_index(op.f('ix_packing_items_category'), table_name='packing_items')
    op.drop_table('packing_items')
    op.drop_index(op.f('ix_checklist_items_is_completed'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_due_date'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_packing_lists_trip_id'), table_name='packing_lists')
    op.drop_index(op.f('ix_packing_lists_id'), table_name='packing_lists')
    op.drop_index(op.f('ix_packing_lists_created_by'), table_name='packing_lists')
    op.drop_table('packing_lists')
    op.drop_index(op.f('ix_checklists_trip_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_created_by'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_checklist_type'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_budget_categories_trip_id'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_id'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_category'), table_name='budget_categories')
    op.drop_table('budget_categories')
    # ### end Alembic commands ###
