"""add_accommodations_and_transits_tables

Revision ID: d486d45f5ea2
Revises: f376b0e51c77
Create Date: 2025-11-09 13:49:38.835619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd486d45f5ea2'
down_revision: Union[str, None] = 'f376b0e51c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_day_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_type', sa.Enum('CHECK_IN', 'WHOLE_DAY', 'CHECK_OUT', name='accommodation_type'), nullable=False),
    sa.Column('check_in_time', sa.Integer(), nullable=True),
    sa.Column('check_out_time', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('confirmation_number', sa.String(length=100), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_accommodation_type'), 'accommodations', ['accommodation_type'], unique=False)
    op.create_index(op.f('ix_accommodations_confirmation_number'), 'accommodations', ['confirmation_number'], unique=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('ix_accommodations_trip_day_id'), 'accommodations', ['trip_day_id'], unique=False)
    op.create_table('transits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_day_id', sa.Integer(), nullable=False),
    sa.Column('transit_mode', sa.Enum('FLIGHT', 'TRAIN', 'BUS', 'CAR', 'BOAT', 'FERRY', 'BIKE', 'WALK', 'OTHER', name='transit_mode_enum'), nullable=False),
    sa.Column('carrier', sa.String(length=200), nullable=True),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('from_location', sa.String(length=200), nullable=True),
    sa.Column('to_location', sa.String(length=200), nullable=True),
    sa.Column('from_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('from_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('to_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('to_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('departure_time', sa.Integer(), nullable=True),
    sa.Column('arrival_time', sa.Integer(), nullable=True),
    sa.Column('departure_timezone', sa.String(length=50), nullable=True),
    sa.Column('arrival_timezone', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('confirmation_number', sa.String(length=100), nullable=True),
    sa.Column('ticket_number', sa.String(length=100), nullable=True),
    sa.Column('seat', sa.String(length=50), nullable=True),
    sa.Column('gate', sa.String(length=20), nullable=True),
    sa.Column('terminal', sa.String(length=50), nullable=True),
    sa.Column('booking_class', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transits_confirmation_number'), 'transits', ['confirmation_number'], unique=False)
    op.create_index(op.f('ix_transits_id'), 'transits', ['id'], unique=False)
    op.create_index(op.f('ix_transits_transit_mode'), 'transits', ['transit_mode'], unique=False)
    op.create_index(op.f('ix_transits_trip_day_id'), 'transits', ['trip_day_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.alter_column('trip_days', 'weather_forecast',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('trip_days', 'transit_mode')
    op.drop_column('trip_days', 'accommodation_checkin')
    op.drop_column('trip_days', 'transit_details')
    op.drop_column('trip_days', 'accommodation_checkout')
    op.drop_column('trip_days', 'accommodation_name')
    op.drop_column('trip_days', 'accommodation_confirmation')
    op.drop_column('trip_days', 'arrival_time')
    op.drop_column('trip_days', 'accommodation_address')
    op.drop_column('trip_days', 'departure_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_days', sa.Column('departure_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('accommodation_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('arrival_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('accommodation_confirmation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('accommodation_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('accommodation_checkout', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('transit_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('trip_days', sa.Column('accommodation_checkin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip_days', sa.Column('transit_mode', postgresql.ENUM('FLIGHT', 'TRAIN', 'BUS', 'CAR', 'BOAT', 'FERRY', 'BIKE', 'WALK', 'OTHER', name='transit_mode'), autoincrement=False, nullable=True))
    op.alter_column('trip_days', 'weather_forecast',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_transits_trip_day_id'), table_name='transits')
    op.drop_index(op.f('ix_transits_transit_mode'), table_name='transits')
    op.drop_index(op.f('ix_transits_id'), table_name='transits')
    op.drop_index(op.f('ix_transits_confirmation_number'), table_name='transits')
    op.drop_table('transits')
    op.drop_index(op.f('ix_accommodations_trip_day_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_confirmation_number'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_accommodation_type'), table_name='accommodations')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
