"""Add User, Trip, and TripDay models

Revision ID: de62e79151a2
Revises: 
Create Date: 2025-11-08 10:42:48.915099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de62e79151a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_photo_url', sa.Text(), nullable=True),
    sa.Column('start_date_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('start_timezone', sa.String(length=50), nullable=False),
    sa.Column('end_date_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('end_timezone', sa.String(length=50), nullable=False),
    sa.Column('dates_confirmed', sa.Boolean(), nullable=False),
    sa.Column('planned_start_year', sa.Integer(), nullable=True),
    sa.Column('planned_start_month', sa.Integer(), nullable=True),
    sa.Column('planned_start_week', sa.String(length=10), nullable=True),
    sa.Column('planned_duration_days', sa.Integer(), nullable=True),
    sa.Column('date_flexibility', sa.String(length=50), nullable=True),
    sa.Column('flexible_date_notes', sa.Text(), nullable=True),
    sa.Column('primary_destination_country', sa.String(length=100), nullable=True),
    sa.Column('primary_destination_city', sa.String(length=100), nullable=True),
    sa.Column('countries_visited', sa.JSON(), nullable=False),
    sa.Column('cities_visited', sa.JSON(), nullable=False),
    sa.Column('trip_type', sa.String(length=20), nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNING', 'UPCOMING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status'), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('budget_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('clones_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_created_by'), 'trips', ['created_by'], unique=False)
    op.create_index(op.f('ix_trips_deleted_at'), 'trips', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_trips_end_date_timestamp'), 'trips', ['end_date_timestamp'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_start_date_timestamp'), 'trips', ['start_date_timestamp'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_visibility'), 'trips', ['visibility'], unique=False)
    op.create_table('trip_days',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_type', postgresql.ENUM('TRANSIT', 'SIGHTSEEING', 'LEISURE', 'ACTIVITY', 'CULTURAL', 'ADVENTURE', 'CULINARY', 'SHOPPING', 'BUSINESS', 'EXPLORATION', 'REST', 'MIXED', name='trip_day_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=False),
    sa.Column('place_city', sa.String(length=100), nullable=True),
    sa.Column('place_country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('transit_mode', postgresql.ENUM('FLIGHT', 'TRAIN', 'BUS', 'CAR', 'BOAT', 'FERRY', 'BIKE', 'WALK', 'OTHER', name='transit_mode'), nullable=True),
    sa.Column('transit_details', sa.JSON(), nullable=False),
    sa.Column('arrival_time', sa.BigInteger(), nullable=True),
    sa.Column('departure_time', sa.BigInteger(), nullable=True),
    sa.Column('accommodation_name', sa.String(length=200), nullable=True),
    sa.Column('accommodation_address', sa.Text(), nullable=True),
    sa.Column('accommodation_checkin', sa.BigInteger(), nullable=True),
    sa.Column('accommodation_checkout', sa.BigInteger(), nullable=True),
    sa.Column('accommodation_confirmation', sa.String(length=100), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('bookings', sa.JSON(), nullable=False),
    sa.Column('weather_forecast', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'date', name='uq_trip_date')
    )
    op.create_index(op.f('ix_trip_days_date'), 'trip_days', ['date'], unique=False)
    op.create_index(op.f('ix_trip_days_day_type'), 'trip_days', ['day_type'], unique=False)
    op.create_index(op.f('ix_trip_days_id'), 'trip_days', ['id'], unique=False)
    op.create_index(op.f('ix_trip_days_place_city'), 'trip_days', ['place_city'], unique=False)
    op.create_index(op.f('ix_trip_days_place_country'), 'trip_days', ['place_country'], unique=False)
    op.create_index(op.f('ix_trip_days_trip_id'), 'trip_days', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_days_trip_id'), table_name='trip_days')
    op.drop_index(op.f('ix_trip_days_place_country'), table_name='trip_days')
    op.drop_index(op.f('ix_trip_days_place_city'), table_name='trip_days')
    op.drop_index(op.f('ix_trip_days_id'), table_name='trip_days')
    op.drop_index(op.f('ix_trip_days_day_type'), table_name='trip_days')
    op.drop_index(op.f('ix_trip_days_date'), table_name='trip_days')
    op.drop_table('trip_days')
    op.drop_index(op.f('ix_trips_visibility'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_start_date_timestamp'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_end_date_timestamp'), table_name='trips')
    op.drop_index(op.f('ix_trips_deleted_at'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_by'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
