"""Add activities and bookings tables

Revision ID: f376b0e51c77
Revises: de62e79151a2
Create Date: 2025-11-09 09:30:03.111794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f376b0e51c77'
down_revision: Union[str, None] = 'de62e79151a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enums explicitly
    op.execute("CREATE TYPE activity_type AS ENUM ('sightseeing', 'dining', 'adventure', 'cultural', 'entertainment', 'shopping', 'relaxation', 'transportation', 'accommodation', 'business', 'other')")
    op.execute("CREATE TYPE activity_status AS ENUM ('planned', 'booked', 'completed', 'cancelled')")
    op.execute("CREATE TYPE booking_type AS ENUM ('accommodation', 'restaurant', 'tour', 'transportation', 'entertainment', 'attraction', 'service', 'rental', 'other')")
    op.execute("CREATE TYPE booking_status AS ENUM ('pending', 'confirmed', 'completed', 'cancelled')")

    # Define enum objects for use in table columns (create_type=False since we already created them)
    activity_type_enum = postgresql.ENUM(
        'sightseeing', 'dining', 'adventure', 'cultural', 'entertainment',
        'shopping', 'relaxation', 'transportation', 'accommodation', 'business', 'other',
        name='activity_type', create_type=False
    )

    activity_status_enum = postgresql.ENUM(
        'planned', 'booked', 'completed', 'cancelled',
        name='activity_status', create_type=False
    )

    booking_type_enum = postgresql.ENUM(
        'accommodation', 'restaurant', 'tour', 'transportation',
        'entertainment', 'attraction', 'service', 'rental', 'other',
        name='booking_type', create_type=False
    )

    booking_status_enum = postgresql.ENUM(
        'pending', 'confirmed', 'completed', 'cancelled',
        name='booking_status', create_type=False
    )

    # Create activities table
    op.create_table(
        'activities',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('trip_day_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('activity_type', activity_type_enum, nullable=False),
        sa.Column('time', sa.String(length=5), nullable=True),
        sa.Column('duration', sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('location_address', sa.Text(), nullable=True),
        sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
        sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
        sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('booking_required', sa.Boolean(), nullable=False),
        sa.Column('confirmation_number', sa.String(length=100), nullable=True),
        sa.Column('booking_url', sa.Text(), nullable=True),
        sa.Column('contact_phone', sa.String(length=50), nullable=True),
        sa.Column('contact_email', sa.String(length=255), nullable=True),
        sa.Column('status', activity_status_enum, nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_id', 'activities', ['id'])
    op.create_index('ix_activities_trip_day_id', 'activities', ['trip_day_id'])
    op.create_index('ix_activities_activity_type', 'activities', ['activity_type'])
    op.create_index('ix_activities_status', 'activities', ['status'])

    # Create bookings table
    op.create_table(
        'bookings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('trip_day_id', sa.Integer(), nullable=True),
        sa.Column('activity_id', sa.Integer(), nullable=True),
        sa.Column('booking_type', booking_type_enum, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('provider', sa.String(length=200), nullable=True),
        sa.Column('confirmation_number', sa.String(length=100), nullable=True),
        sa.Column('booking_reference', sa.String(length=100), nullable=True),
        sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('booking_date', sa.Date(), nullable=True),
        sa.Column('booking_time', sa.String(length=5), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('location_address', sa.Text(), nullable=True),
        sa.Column('contact_phone', sa.String(length=50), nullable=True),
        sa.Column('contact_email', sa.String(length=255), nullable=True),
        sa.Column('booking_url', sa.Text(), nullable=True),
        sa.Column('status', booking_status_enum, nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_id', 'bookings', ['id'])
    op.create_index('ix_bookings_trip_day_id', 'bookings', ['trip_day_id'])
    op.create_index('ix_bookings_activity_id', 'bookings', ['activity_id'])
    op.create_index('ix_bookings_booking_type', 'bookings', ['booking_type'])
    op.create_index('ix_bookings_confirmation_number', 'bookings', ['confirmation_number'])

    # Drop old JSON columns from trip_days
    op.drop_column('trip_days', 'bookings')
    op.drop_column('trip_days', 'activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back JSON columns to trip_days
    op.add_column('trip_days', sa.Column('activities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default='[]'))
    op.add_column('trip_days', sa.Column('bookings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default='[]'))

    # Drop indexes
    op.drop_index('ix_bookings_confirmation_number', 'bookings')
    op.drop_index('ix_bookings_booking_type', 'bookings')
    op.drop_index('ix_bookings_activity_id', 'bookings')
    op.drop_index('ix_bookings_trip_day_id', 'bookings')
    op.drop_index('ix_bookings_id', 'bookings')
    op.drop_index('ix_activities_status', 'activities')
    op.drop_index('ix_activities_activity_type', 'activities')
    op.drop_index('ix_activities_trip_day_id', 'activities')
    op.drop_index('ix_activities_id', 'activities')

    # Drop tables
    op.drop_table('bookings')
    op.drop_table('activities')

    # Drop enums
    op.execute("DROP TYPE IF EXISTS booking_status")
    op.execute("DROP TYPE IF EXISTS booking_type")
    op.execute("DROP TYPE IF EXISTS activity_status")
    op.execute("DROP TYPE IF EXISTS activity_type")
    # ### end Alembic commands ###
